spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/bobomico_cloud?useUnicode=true&characterEncoding=UTF-8
  jpa:
    show-sql: true

server:
  port: 8082
  servlet:
    context-path: /bobomico

PRODUCT:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

env: love 123456
